#!/bin/bash

CARD="/usr/share/xact/card1"
LOGFILE="$CARD/xact-init.log"

df
mount -a

{
if mount | grep $CARD > /dev/null; then
  date
  # Card is mounted
  if [[ -f $CARD/commands.txt ]]; then
    # Has commands
    xact-run logo
    while true; do
      cmd=()
      while IFS= read -r line; do
        cmd+=("$line")
      done <<< $(xact-commands-txt.py peek $CARD/commands.txt)
      echo $cmd
      echo ${cmd[0]}
      echo ${cmd[1]}
        if [[ ${cmd[0]} == "e" ]]; then
	  break
        fi
	xact-run ${cmd[1]}
	exit_code=$?
	echo Exit code: $exit_code
	if [[ ${cmd[0]} != *"?"* ]]; then
	  if [[ $exit_code != 0 ]]; then
            echo "Command failed: ${cmd[1]}"
            xact-run disp "Command failed:\n${cmd[1]}"
            exit $exit_code
	  fi
	fi
        xact-commands-txt.py pop $CARD/commands.txt
    done
  else
    # No commands file
    echo "No commands file found" | tee $LOGFILE
  fi
fi

}
# >> $LOGFILE 2>&1

xact-run docker-start
exit_code=$?
if [[ $exit_code != 0 ]]; then
  xact-run disp "Could not start container"
fi
xact-run docker-launch
exit_code=$?
if [[ $exit_code != 0 ]]; then
  xact-run disp "Could not launch container"
fi

